spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Specific route for unreliable endpoint with circuit breaker and fallback
            - id: service-provider-unreliable
              uri: lb://SERVICE-PROVIDER
              predicates:
                - Path=/service-provider/api/unreliable
              filters:
                - StripPrefix=1
                - CircuitBreaker=name=providerUnreliableCb,fallbackUri=forward:/fallback/provider-unreliable
            # Generic route for provider
            - id: service-provider
              uri: lb://SERVICE-PROVIDER
              predicates:
                - Path=/service-provider/**
            # Generic route for consumer
            - id: service-consumer
              uri: lb://SERVICE-CONSUMER
              predicates:
                - Path=/service-consumer/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://localhost:4317
      transport: grpc

server:
  port: 8082

logging:
  level:
    org.springframework.cloud.gateway.server.mvc: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
