spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            # Specific route for unreliable endpoint with circuit breaker and fallback
            - id: service-provider-unreliable
              uri: lb://service-provider
              predicates:
                - Path=/provider/api/unreliable
              filters:
                - StripPrefix=1
                - CircuitBreaker=name=providerUnreliableCb,fallbackUri=forward:/fallback/provider-unreliable
            # Generic route for provider
            - id: service-provider
              uri: lb://service-provider
              predicates:
                - Path=/provider/**
              filters:
                - StripPrefix=1
            # Generic route for consumer
            - id: service-consumer
              uri: lb://service-consumer
              predicates:
                - Path=/consumer/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://localhost:4317
      transport: grpc

server:
  port: 8082

logging:
  level:
    org.springframework.cloud.gateway.server.mvc: DEBUG